// <auto-generated />
using System;
using EquipmentRental.Modules.Rentals.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentRental.Modules.Rentals.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RentalsDbContext))]
    [Migration("20260731101422_InitialRentalsPersistence")]
    partial class InitialRentalsPersistence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rentals")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AvailabilityCommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_commitment_id");

                    b.Property<Guid>("EquipmentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_category_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("rental_order_id")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_order_id");

                    b.HasKey("Id");

                    b.HasIndex("rental_order_id");

                    b.ToTable("rental_lines", "rentals");
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("FulfilmentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilment_location_id");

                    b.Property<DateTimeOffset?>("QuoteExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("quote_expires_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("updated_at_utc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("rental_orders", "rentals");
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalLine", b =>
                {
                    b.HasOne("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalOrder", null)
                        .WithMany("Lines")
                        .HasForeignKey("rental_order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EquipmentRental.Modules.Rentals.Domain.RentalOrders.Money", "DailyRate", b1 =>
                        {
                            b1.Property<Guid>("RentalLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("daily_rate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("daily_rate_currency");

                            b1.HasKey("RentalLineId");

                            b1.ToTable("rental_lines", "rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalLineId");
                        });

                    b.Navigation("DailyRate")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalOrder", b =>
                {
                    b.OwnsOne("EquipmentRental.Modules.Rentals.Domain.RentalOrders.Money", "EstimatedTotal", b1 =>
                        {
                            b1.Property<Guid>("RentalOrderId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("estimated_total_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("estimated_total_currency");

                            b1.HasKey("RentalOrderId");

                            b1.ToTable("rental_orders", "rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalOrderId");
                        });

                    b.OwnsOne("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("RentalOrderId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndExclusive")
                                .HasColumnType("date")
                                .HasColumnName("rental_end_exclusive");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("rental_start");

                            b1.HasKey("RentalOrderId");

                            b1.ToTable("rental_orders", "rentals");

                            b1.WithOwner()
                                .HasForeignKey("RentalOrderId");
                        });

                    b.Navigation("EstimatedTotal");

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.Domain.RentalOrders.RentalOrder", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
