// <auto-generated />
using System;
using EquipmentRental.Modules.Rentals.ProcessManagers.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentRental.Modules.Rentals.ProcessManagers.Persistence.Migrations
{
    [DbContext(typeof(RentalConfirmationProcessDbContext))]
    [Migration("20260731112930_InitialRentalConfirmationProcess")]
    partial class InitialRentalConfirmationProcess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rentals_process_manager")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.ProcessManagers.Persistence.RentalConfirmationProcess", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ClaimedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until_utc");

                    b.Property<DateTimeOffset>("DeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline_utc");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failure_code");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<Guid>("RentalOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_order_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("RentalOrderId")
                        .IsUnique()
                        .HasDatabaseName("ux_confirmation_process_rental_order");

                    b.ToTable("rental_confirmation_processes", "rentals_process_manager");
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.ProcessManagers.Persistence.RentalConfirmationStep", b =>
                {
                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<Guid>("RentalLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("rental_line_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("CommitmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("commitment_id");

                    b.Property<DateOnly>("EndDateExclusive")
                        .HasColumnType("date")
                        .HasColumnName("end_date_exclusive");

                    b.Property<Guid>("EquipmentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_category_id");

                    b.Property<Guid>("FulfilmentLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("fulfilment_location_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("RejectionCode")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rejection_code");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("ProcessId", "RentalLineId");

                    b.ToTable("rental_confirmation_steps", "rentals_process_manager");
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.ProcessManagers.Persistence.RentalConfirmationStep", b =>
                {
                    b.HasOne("EquipmentRental.Modules.Rentals.ProcessManagers.Persistence.RentalConfirmationProcess", null)
                        .WithMany("Steps")
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentRental.Modules.Rentals.ProcessManagers.Persistence.RentalConfirmationProcess", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
