// <auto-generated />
using System;
using EquipmentRental.Modules.FleetAvailability.ReadModel.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentRental.Modules.FleetAvailability.ReadModel.Persistence.Migrations
{
    [DbContext(typeof(AvailabilityCalendarDbContext))]
    partial class AvailabilityCalendarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fleet_availability_read")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.ReadModel.Persistence.AvailabilityDayProjection", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("CommittedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("committed_quantity");

                    b.Property<DateTimeOffset>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at_utc");

                    b.HasKey("ScheduleId", "Date");

                    b.ToTable("availability_days", "fleet_availability_read");
                });

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.ReadModel.Persistence.AvailabilityScheduleProjection", b =>
                {
                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<Guid>("EquipmentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_category_id");

                    b.Property<DateTimeOffset>("LastEventAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_at_utc");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.HasKey("ScheduleId");

                    b.HasIndex("EquipmentCategoryId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_availability_schedules_category_location");

                    b.ToTable("availability_schedules", "fleet_availability_read");
                });

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.ReadModel.Persistence.ProjectionInboxMessage", b =>
                {
                    b.Property<string>("Consumer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("consumer");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.HasKey("Consumer", "MessageId");

                    b.ToTable("inbox_messages", "fleet_availability_read");
                });
#pragma warning restore 612, 618
        }
    }
}
