// <auto-generated />
using System;
using EquipmentRental.Modules.FleetAvailability.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EquipmentRental.Modules.FleetAvailability.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FleetAvailabilityDbContext))]
    [Migration("20260731114753_AddOutboxDeadLetter")]
    partial class AddOutboxDeadLetter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("fleet_availability")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EquipmentRental.BuildingBlocks.Eventing.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<Guid?>("ClaimedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("claimed_by");

                    b.Property<DateTimeOffset?>("ClaimedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_until_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset?>("DeadLetteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset>("NextAttemptAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at_utc");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc", "NextAttemptAtUtc")
                        .HasDatabaseName("ix_outbox_messages_pending");

                    b.ToTable("outbox_messages", "fleet_availability");
                });

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.Domain.Schedules.AvailabilityCommitment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DemandId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_demand_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("released_at_utc");

                    b.Property<Guid>("availability_schedule_id")
                        .HasColumnType("uuid")
                        .HasColumnName("availability_schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("DemandId")
                        .IsUnique()
                        .HasDatabaseName("ux_availability_commitments_external_demand");

                    b.HasIndex("availability_schedule_id");

                    b.ToTable("availability_commitments", "fleet_availability");
                });

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.Domain.Schedules.AvailabilitySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EquipmentCategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipment_category_id");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<DateTimeOffset>("updated_at_utc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCategoryId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ux_availability_schedules_category_location");

                    b.ToTable("availability_schedules", "fleet_availability");
                });

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.Domain.Schedules.AvailabilityCommitment", b =>
                {
                    b.HasOne("EquipmentRental.Modules.FleetAvailability.Domain.Schedules.AvailabilitySchedule", null)
                        .WithMany("Commitments")
                        .HasForeignKey("availability_schedule_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("EquipmentRental.Modules.FleetAvailability.Domain.Schedules.AvailabilityPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("AvailabilityCommitmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EndExclusive")
                                .HasColumnType("date")
                                .HasColumnName("commitment_end_exclusive");

                            b1.Property<DateOnly>("Start")
                                .HasColumnType("date")
                                .HasColumnName("commitment_start");

                            b1.HasKey("AvailabilityCommitmentId");

                            b1.ToTable("availability_commitments", "fleet_availability");

                            b1.WithOwner()
                                .HasForeignKey("AvailabilityCommitmentId");
                        });

                    b.Navigation("Period")
                        .IsRequired();
                });

            modelBuilder.Entity("EquipmentRental.Modules.FleetAvailability.Domain.Schedules.AvailabilitySchedule", b =>
                {
                    b.Navigation("Commitments");
                });
#pragma warning restore 612, 618
        }
    }
}
